### ISSUE TITLE
Easy Buttons

### ISSUE THREAD

**Issue by soatok** [CyberFurz/furryfediverse-site#49]
There should be two easy buttons:

1. For each instance, a "Take me to the registration form" button. So they don't have to visit instance _then_ locate the registration form link on the subsequent webpage.
2. A button at the top for "I don't care about instances, choose one for me" for users who feel that "choosing an instance" is too much cognitive load and are thus fediverse-adverse.

**Comment by hack13** [comment]
Registration form link should be easy for Mastodon servers however not as easy to accomplish with Misskey/Calckey servers as they do that via a model I might just update the buttons to be "Sign Up" and if mastodon it will send you to the registration page, otherwise it will toss you to the landing page.

As for "I don't care" will require me to think a bit where we send people upon clicking it... like obviously a general instance would be ideal... but I don't want them ending up on an instance that isn't vetted... but then I get into the politics of picking a list of "Vetted" instances that would be safe to offload users onto...

This is def food for thought, I will get something cooked up as soon as I am off work today and pushed for this as it seems like a pretty quick thing to shove out into traffic.

**Comment by gmemstr** [comment]
What about an option for admins to provide a custom invite link that furryfediverse directs to? I don't know what other platforms offer but at least it would let people see how the page is doing. As an admin I'd find this useful at least.

I do agree that a "I don't care" feature is tricky, especially with the number of instances that may be very focused on a particular topic. Maybe it just selects 2-3, one or two from the general section and one from the focused? (Or just from the general)?

**Comment by soatok** [comment]
> As for "I don't care" will require me to think a bit where we send people upon clicking it... like obviously a general instance would be ideal... but I don't want them ending up on an instance that isn't vetted... but then I get into the politics of picking a list of "Vetted" instances that would be safe to offload users onto...

If you don't care, they don't either.

Use Math.random() client-side to pick any of the servers with open registration.

**Comment by hack13** [comment]
I have added an "easy button" as recomended by this

**Comment by hack13** [comment]
This issue has been completed, as there is now an "easy button" as for the other feature I am rolling that into our storyboard for in V2 which I am working today. So with that said, this feature is technically done for the current version.
