### ISSUE TITLE
Unable to restore instance

### ISSUE THREAD

**Issue by InariTheFox** [CyberFurz/furryfediverse-site#50]
Our instance has been unlisted for quite some time, and attempts to contact the developers through their mastodon instances has resulted in either no communication or a response that someone will look in to it.

Given that the Furry Fediverse site is the essential starting point, we need our site to be relisted.

Please help with returning the squeaky.social (NOT squeak.social) site to the listing. Thank you!

**Comment by hack13** [comment]
Apologies, I didn't get a message from you before. We do have automated system that removes instances that fail to check in over time due to downtime. I haven't really had much time to work on this previously, but I will look into getting this fixed in the current version soon as you are not the only instance to fall victim to downtime resulting in removal.

I will update this function to recheck every couple hours on any instances that are removed due to failed check-ins. Apologies for this.

**Comment by hack13** [comment]
Pushed a fix for retries, set up a cronjob that will run against failed instances every hour to see if they have come back. https://github.com/CyberFurz/furryfediverse-site/issues/50
